name: Build and Store App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create build directory
        run: mkdir build

      - name: Copy APK to build directory
        run: cp app/build/outputs/apk/debug/app-debug.apk build/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: build/